### ISSUE TITLE
Remove babel

### ISSUE THREAD

**Issue by henrybarreto** [henrybarreto/linkly#2]
Use, instead of babel, the new node's features.

**Comment by JAYESH8011** [comment]
hey, can I fix this issue

**Comment by henrybarreto** [comment]
> hey, can I fix this issue

Sorry, Mate. I've made this fixing without checking the responses.

**Comment by henrybarreto** [comment]
> hey, can I fix this issue

Would you like to help on this one?
https://github.com/henrybarreto/linkly/issues/5
